theme: jekyll-theme-cayman
title: "<a href='https://rocknroll87q.github.io/NeuroFM/'>NeuroFM</a>"
description: "Toward Precision Neuroimaging with Foundation Models for Individualized Brain Health Estimation"

show_downloads: true

github:
  zip_url: https://github.com/rockNroll87q/NeuroFM/
  another_url: https://doi.org/10.64898/2026.03.27.26349489
